version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    ports:
      - "4036:4036"
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=sqlite+aiosqlite:///./data/magnetiq.db
      - DEBUG=true
      - SECRET_KEY=dev-secret-key-change-in-production
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./media:/app/media
    command: uvicorn app.main:app --host 0.0.0.0 --port 4036 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4036/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "9036:9036"
    environment:
      - VITE_API_URL=http://localhost:4036
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./media:/var/www/media:ro
    depends_on:
      - backend
      - frontend
    profiles:
      - production

volumes:
  data:
  media: