apiVersion: v1
kind: ServiceAccount
metadata:
  name: magnetiq-sa
  namespace: magnetiq-v2
  labels:
    app: magnetiq
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: magnetiq-v2
  name: magnetiq-role
  labels:
    app: magnetiq
rules:
# Allow reading pods for health checks and monitoring
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
# Allow reading services for service discovery
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
# Allow reading configmaps for configuration
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Allow reading secrets for sensitive configuration
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
# Allow reading deployments for monitoring
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
# Allow reading persistent volume claims
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: magnetiq-rolebinding
  namespace: magnetiq-v2
  labels:
    app: magnetiq
subjects:
- kind: ServiceAccount
  name: magnetiq-sa
  namespace: magnetiq-v2
roleRef:
  kind: Role
  name: magnetiq-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: magnetiq-cluster-role
  labels:
    app: magnetiq
rules:
# Allow reading nodes for cluster information
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
# Allow reading namespaces
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: magnetiq-cluster-rolebinding
  labels:
    app: magnetiq
subjects:
- kind: ServiceAccount
  name: magnetiq-sa
  namespace: magnetiq-v2
roleRef:
  kind: ClusterRole
  name: magnetiq-cluster-role
  apiGroup: rbac.authorization.k8s.io