apiVersion: v1
kind: Secret
metadata:
  name: magnetiq-secrets
  namespace: magnetiq-v2
type: Opaque
stringData:
  # Security Keys
  SECRET_KEY: "your-production-secret-key-change-this-before-deployment"
  ALGORITHM: "HS256"
  
  # SMTP Credentials (Replace with actual credentials)
  SMTP_USERNAME: "sysadmin@euroblaze.de"
  SMTP_PASSWORD: "your-smtp-password-here"
  
  # Database Password (if using PostgreSQL in future)
  DATABASE_PASSWORD: ""
  
  # Container Registry Credentials (if private)
  REGISTRY_USERNAME: ""
  REGISTRY_PASSWORD: ""